on: [push]

jobs:
  main:
    name: Build and Publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Install dependencies
      #   run: pip3 install mkdocs-material
      - name: Build and Deploy
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CONFIG_FILE: ${{ github.workspace }}/mkdocs.yml